import { Timestamp } from 'firebase/firestore';

export interface VideoMetadata {
  id: string;
  title: string;
  description?: string;
  creatorId: string;
  videoUrl?: string;
  thumbnailUrl?: string;
  status: 'uploading' | 'processing' | 'ready' | 'error';
  createdAt: Date;
  updatedAt: Date;
  size: number;
  mimeType: string;
  duration: number;
  category?: string;
  tags?: string[];
  isPublic: boolean;
  language: string;
  difficulty?: string;
  views: number;
  likes: number;
}

export interface VideoUploadOptions {
  title: string;
  description?: string;
  category?: string;
  tags?: string[];
  isPublic?: boolean;
  language?: string;
  difficulty?: string;
  onProgress?: (progress: UploadProgress) => void;
}

export interface VideoUploadResponse {
  videoId: string;
  downloadUrl: string;
  thumbnailUrl?: string;
  duration?: number;
}

export interface VideoUploadProgress {
  bytesTransferred: number;
  totalBytes: number;
  progress: number;
  status: 'uploading' | 'processing' | 'complete' | 'error';
}

/**
 * @deprecated Use VideoUploadProgress instead
 */
export interface UploadProgress {
  progress: number;
  bytesTransferred: number;
  totalBytes: number;
  error?: Error;
}

/**
 * Error codes for video-related operations
 */
export type VideoErrorCode = 
  | 'video/invalid-format'
  | 'video/too-large'
  | 'video/processing-failed'
  | 'video/invalid-type'
  | 'video/file-too-large'
  | 'video/upload-failed'
  | 'auth/not-authenticated'
  | 'auth/not-authorized'
  | 'audio/ffmpeg-load-failed'
  | 'audio/extraction-failed'
  | 'audio/invalid-format'
  | 'audio/too-large'
  | 'audio/processing-failed'
  | 'audio/chunk-failed'
  | 'audio/permission-denied'
  | 'audio/recording-failed'
  | 'audio/playback-failed';

/**
 * Custom error class for video-related operations
 */
export class VideoError extends Error {
  readonly code: VideoErrorCode;

  constructor(message: string, code: VideoErrorCode) {
    super(message);
    this.code = code;
    this.name = 'VideoError';
  }
}

export interface VideoBookmark {
  id: string;
  userId: string;
  videoId: string;
  timestamp: number;  // Position in video (milliseconds)
  label: string;
  notes?: string;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

export interface VideoNote {
  id: string;
  userId: string;
  videoId: string;
  timestamp: number;  // Position in video (milliseconds)
  content: string;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

export interface VideoUploadResult {
  success: boolean;
  videoId: string;
  metadata: VideoMetadata;
}

export interface ProcessingServerRequest {
  videoId: string;
  videoUrl: string;
  userId: string;
  message?: string;
}

export interface ProcessingServerResponse {
  status: 'success' | 'error';
  message: string;
  data?: {
    jobId: string;
    videoId: string;
    userId: string;
    metadata: {
      duration?: number;
      thumbnailUrl?: string;
      transcript?: VideoTranscript;
    };
    timestamp: number;
    processingTime: number;
    clientMessage?: string;
  };
  timestamp: number;
  requestId?: string;
}

export interface VideoTranscript {
  videoId: string;
  segments: Array<{
    startTime: number;
    endTime: number;
    text: string;
    speakerId?: string;
  }>;
  language: string;
  isAutogenerated: boolean;
} 